language: cpp
compiler:
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
script:
    - julia -e 'Pkg.init(); Pkg.add("Cairo"); Pkg.add("RDatasets")'
    - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("Gadfly"))`); Pkg.pin("Gadfly"); Pkg.resolve()'
    - julia ~/.julia/Gadfly/tests/test.jl
comment:
    - Go travis go
